 
CREATE TABLE AuditLogs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TransactionId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Transactions(Id),
    Action NVARCHAR(50) NOT NULL,
    PerformedBy NVARCHAR(100) NOT NULL,
    Timestamp DATETIME2 NOT NULL
);
