CREATE TABLE Banks (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    ApiEndpoint NVARCHAR(500) NOT NULL,
    CountryId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL
);