 
CREATE TABLE Transactions (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    MerchantId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Merchants(Id),
    BankId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Banks(Id),
    UserId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Users(Id),
    PaymentId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Payment(Id),
    CreditCardNumber NVARCHAR(16) NOT NULL,
    Amount DECIMAL(18, 2) NOT NULL,
    Currency NVARCHAR(10) NOT NULL,
    ClientIp NVARCHAR(20) NOT NULL,
    AccountCurrency NVARCHAR(10) NULL,  
    Status NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME2 NOT NULL,
    UpdatedAt DATETIME2 NULL,
    IsHighRisk BIT NOT NULL
);

 